src/optional/index.js

Useful for representing optional properties in Flow, which are of type
`T | void`.
https://flow.org/en/docs/types/objects/#toc-optional-object-type-properties

Add `fake.optional`

---

package.json
yarn.lock

In some cases I had to hand-edit the yarn.lock file. 🤢

Upgrade lodash & sub-dependencies to address major & medium vulnerabilities

---

index.d.ts
src/sentence/index.js
src/word/index.js

`fake.word`: useful to generate strings without white spaces
`fake.sentence`: useful to generate strings with multiple words
Why?
`fake.string` generate strings with double spaces within the content and end spaces.
Reference: https://github.com/goodeggs/fake-eggs/pull/35#issuecomment-572263004

add: fake word and fake sentence

---

readme.md
src/index.js

The new functions weren't exported by the index. To use it we currently need to set the complete folder path(e.g. `fake-eggs/word`).
- Added `word` and `sentence` export in the file `index`;
- `yarn build` to regenerate the readme;

fix: add the word and sentence exports on the index

---

CHANGELOG.md

This just confused me for several minutes. It looks like some tests were incorrectly interpreting the second argument as an inclusive bound and doing impossible things like:
```js
fake.array(3, 3, () => foo)
```

docs: add fake.array notice to v5 changelog entry

---

package.json
readme.md
src/generators/zip/index.ts
src/index.test.ts
src/index.ts

In https://github.com/goodeggs/marketplace-mobile-app/pull/244 we need to replace `faker.address.zip` with `fake-eggs`, but in `fake-eggs` we don't have a zip code generator.
[#173755442]

Add zip codes 

---

package.json

Apparently any external types you reference in your published declaration file have to be included as dependencies of your module (by being regulart dependencies).
(This took me way too long to figure out. It seems somewhat obvious in hindsight, but this doesn't appear to be documented anywhere... Though now that I know what to look for, I found it documented here: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html. Oh well.)
The funny thing is the only actual reference to Chance types in the declaration file [is incorrect](https://github.com/goodeggs/fake-eggs/pull/45#discussion_r454397535) and shouldn't be there in the first place.

fix: make Typescript declaration file actually valid

---

package.json
src/utils/index.ts

When we need to create a slug, we need to use only alphanumeric characters, so we need to ignore dashes and hyphens

Change slugify to remove dashes and hyphens

---

package.json
src/generators/foodhub/index.ts

In [goodegg-foodhubs v5](https://github.com/goodeggs/goodeggs-foodhubs/releases/tag/v5.0.0), we've removed `tomorrowland` as a `foodhub`. This is causing tests to flake when `tomorrowland` is returned by `fake.foodhub.slug()`, in order to fix this PR attempts to bring the list of possible `foodhubSlugs` to reflect to most up to date [foodhubs](https://github.com/goodeggs/goodeggs-foodhubs/blob/master/src/index.ts).
- feat: updated possible `foodhubSlugs`
cc: @hsingh6764

feat: update list of possible foodhub slugs

---

readme.md

docs: remove broken Greenkeeper badge from README

---

.dependabot/config.yml
.eslintrc.js
package.json
src/generators/email/index.ts
src/generators/producer/index.ts
yarn.lock

- upgrade misc. patch/minor deps
- upgrade to TypeScript 4 and latest @goodeggs/toolkit, which includes latest eslint-plugin-goodeggs and support for TypeScript 4; fix new errors
- add Dependabot config as recommended by https://goodeggs.atlassian.net/wiki/spaces/ENG/pages/553058598/Dependabot, which auto-merged in-range bumps

chore: upgrade all dependencies and add Dependabot config

---

package.json
src/generators/integer/index.test.ts
src/generators/integer/index.ts

By default, Chance.js would use range -9007199254740991 (-2^53 - 1) to 9007199254740991 (2^53 - 1).  See https://chancejs.com/basics/integer.html.
However, per the GraphQL spec, Integers are only treated as valid when they are representable as a 32-bit signed integer, providing the broadest support across platforms.
It doesn't seem worthwhile to provide two separate integer functions in fake-eggs, nor to require thousands of calls to `fake.integer()` across apps that use GraphQL (Garbanzo and Catalog API, today) to pass in ranges to deal with this inconsistency, so just default to a valid 32-bit signed integer range here.
🍐 with @marco-maturana

feat(integer): generate valid GraphQL integers by default

---

jest.config.js
jest.setup.ts
package.json
src/generators/date/index.test.ts
src/generators/date/index.ts
src/generators/day/index.test.ts
src/generators/day/index.ts
src/index.test.ts
yarn.lock

See various inline comments. Basically, I made two changes:
- narrowed the default range from `[-271821-04-20, +275760-09-13]` to `[1001-01-1, 9999-01-01]`
- it just isn't worthwhile nor pragmatic to continue to support this, IMO
- added runtime validation that provided `from` and `to` args are in the `YYYY-MM-DD` formats, since otherwise we cannot guarantee that the function will work as expected and generate days in the provided range (because allowing `new Date()` to parse arbitrary date formats results in undefined behavior)
- this caused some extremely confusing issues for me a few weeks ago (as a consequence of the above range issue, but still seemed worth solving separately for good measure)

feat(day): narrow default range of fake.day() and validate its args

---

readme.md
src/generators/number/index.test.ts
src/generators/number/index.ts
src/index.test.ts

In order for Garbanzo to migrate away from `faker` and use fake-eggs instead, we need to support the case where a number needs to be generated up to N digits after the decimal point. See example: https://github.com/goodeggs/garbanzo/blob/master/src/domain/accounting/models/factories.js#L18
- chore: added `fixed` (default as 4) as an additional input param when generating `.number()`

chore: configure number generation with precision

---

package.json
src/generators/phone_number/index.ts

Garbanzo's User model expects a phone number with a `+1` prefix, otherwise, [document validation fails](https://github.com/goodeggs/garbanzo/blob/master/src/orzo/server/models/user.js#L226). 
- Prefix `+1` instead of `+` when generating a phone number

fix: ensure (US) phoneNumbers have +1 prefix

---

readme.md
src/generators/state/index.test.ts
src/generators/state/index.ts
src/index.test.ts
src/index.ts

Currently the way we fake state codes in Garbanzo is to generate a random two letter string, without checking if it is a state or not (see [here](https://github.com/goodeggs/garbanzo/blob/master/src/orzo/spec_helpers/factories.js#L69)). It would be more convenient if fake-eggs handled this.

Add 2 letter state generator

---

package.json
readme.md
src/generators/location/index.ts
src/index.test.ts
src/index.ts

v6.4.0 contains:
- https://github.com/goodeggs/fake-eggs/pull/233, that lives under `fake.location.state`
- https://github.com/goodeggs/fake-eggs/pull/231
- Duplicating `fake.address` -> `fake.location.address` and `fake.zip` -> `fake.location.zip` to pad out `fake.location`. We can remove the former in a breaking version update if we'd like.

Add `fake.location` and bump minor version

---

.travis.yml
package.json

The previous one was revoked.
6.4.0 was not successfully published because of this, so this also bumps to 6.4.1

ci: rotate Travis CI NPM token

---

.gitignore
package.json
readme.md
src/index.test.ts
src/index.ts
yarn.lock

fake-eggs is a library for generating realistic Good Eggs random data. It's wrapping an open-source library (chance.js) for generating generic random data of various types.
It seems like a waste that the underlying chance.js library supports hundreds of random data types but accessing these requires opening a fake-eggs PR and mounting a new, unit-tested method, releasing a version, etc.
See https://github.com/goodeggs/fake-eggs/issues/41.
This PR exposes chance.js through the attribute`fake.chance`. This provides devs access to all of chance's functionality, while still keeping all fake data management inside of the fake-eggs library
- This blocks us from switching to a different fake data library other than chance, as we'd need to go through our full codebase and swap out all the …

feat: expose chance

---

readme.md

We removed this in favor of `fake.unique` a couple years ago.

docs(readme): fix outdated function reference in code example
